build:
	docker build -t ohif-healthlake-proxy . --platform linux/amd64
tag:
	docker tag ohif-healthlake-proxy mateusfreira/ohif-healthlake-proxy
publish:
	docker publish mateusfreira/ohif-healthlake-proxy
