build:
	docker build -t ohif-aws-healthimaging-proxy . --platform linux/amd64
tag:
	docker tag ohif-aws-healthimaging-proxy flexview/ohif-aws-healthimaging-proxy
push:
	docker push flexview/ohif-aws-healthimaging-proxy
